---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-web-config
  labels:
    app: contoso-air-web
    component: web-server
    version: v1
    app.kubernetes.io/name: contoso-air
    app.kubernetes.io/component: web-server
    app.kubernetes.io/part-of: contoso-air-platform
    app.kubernetes.io/managed-by: kubectl
data:
  NODE_ENV: "production"
  PORT: "3000"
  # Azure-specific configurations
  AZURE_COSMOS_SCOPE: "https://cosmos.azure.com/.default"
