---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-web
  labels:
    app: contoso-air-web
    component: web-server
    version: v1
    app.kubernetes.io/name: contoso-air
    app.kubernetes.io/component: web-server
    app.kubernetes.io/part-of: contoso-air-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    deployment.kubernetes.io/revision: "1"
    app.kubernetes.io/version: "v1"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: contoso-air-web
  template:
    metadata:
      labels:
        app: contoso-air-web
        component: web-server
        version: v1
        app.kubernetes.io/name: contoso-air
        app.kubernetes.io/component: web-server
        app.kubernetes.io/part-of: contoso-air-platform
        app.kubernetes.io/managed-by: kubectl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: contoso-air-web
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
        sysctls: []
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - contoso-air-web
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - contoso-air-web
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 30
      containers:
        - name: contoso-air-web
          # Pin to specific digest for security (TODO: Replace with digest)
          image: osktestcrqpjmtpx4xyv3e.azurecr.io/contosoair:v1
          # image: osktestcrqpjmtpx4xyv3e.azurecr.io/contosoair@sha256:DIGEST
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: contoso-air-web-config
            - secretRef:
                name: contoso-air-web-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-cache
              mountPath: /var/cache
            - name: var-log
              mountPath: /var/log
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
            successThreshold: 1
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
        - name: var-cache
          emptyDir:
            sizeLimit: 64Mi
        - name: var-log
          emptyDir:
            sizeLimit: 64Mi
