---
apiVersion: v1
kind: Secret
metadata:
  name: contoso-air-web-secrets
  labels:
    app: contoso-air-web
    component: web-server
    version: v1
    app.kubernetes.io/name: contoso-air
    app.kubernetes.io/component: web-server
    app.kubernetes.io/part-of: contoso-air-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # This secret should be created separately with actual values
    config.kubernetes.io/managed-by: "external"
type: Opaque
stringData:
  # Replace these with actual values when deploying
  AZURE_COSMOS_LISTCONNECTIONSTRINGURL: >-
    https://management.azure.com/subscriptions/SUBSCRIPTION_ID/
    resourceGroups/RESOURCE_GROUP/providers/Microsoft.DocumentDB/
    databaseAccounts/ACCOUNT_NAME/listConnectionStrings?api-version=2021-04-15
  AZURE_COSMOS_CLIENTID: "00000000-0000-0000-0000-000000000000"
---
# Alternative: Use Azure Key Vault Secret Provider
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: contoso-air-kv-secrets
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"
#     userAssignedIdentityID: "client-id"
#     keyvaultName: "kv-name"
#     objects: |
#       array:
#         - |
#           objectName: cosmos-connection-string
#           objectType: secret
#         - |
#           objectName: cosmos-client-id
#           objectType: secret
