apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-web
  labels:
    app: contoso-air-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso-air-web
  template:
    metadata:
      labels:
        app: contoso-air-web
    spec:
      containers:
        - name: contoso-air-web
          image: osktestcrqpjmtpx4xyv3e.azurecr.io/pluxee-demo:v1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: contoso-air-web
spec:
  type: ClusterIP
  selector:
    app: contoso-air-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
